"""
UniPath AI - Configuration
Reads secrets from environment variables. Never hardcode API keys here.

Required env var for live LLM calls:
    GROQ_API_KEY

Optional:
    GROQ_MODEL        (default: llama-3.3-70b-versatile)
    UNIPATH_TOP_K      (default: 4)  -> number of RAG chunks retrieved per query
"""

import os


def _get_setting(key: str, default: str = "") -> str:
    """Look for a setting in, in order: real environment variables,
    then Streamlit Cloud secrets (st.secrets). This lets the exact same
    config.py work locally (export GROQ_API_KEY=...) and on Streamlit
    Community Cloud (Settings -> Secrets), without code changes.
    """
    val = os.environ.get(key, "").strip()
    if val:
        return val
    try:
        import streamlit as st  # only import if available (avoids hard dependency)
        if key in st.secrets:
            return str(st.secrets[key]).strip()
    except Exception:
        pass
    return default


# --- LLM / Groq settings ---
GROQ_API_KEY = _get_setting("GROQ_API_KEY", "")
GROQ_MODEL = _get_setting("GROQ_MODEL", "llama-3.3-70b-versatile")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# If no API key is set, the module runs in MOCK MODE:
# agents still work end-to-end (retrieval + reasoning templates),
# but the "AI-written" text is generated by a local template
# instead of a real LLM call. This lets your friend run/demo the
# module immediately, then flip to live mode by just setting GROQ_API_KEY.
MOCK_MODE = GROQ_API_KEY == ""

# --- RAG settings ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KB_DIR = os.path.join(BASE_DIR, "knowledge_base")
TOP_K = int(_get_setting("UNIPATH_TOP_K", "4"))

# --- Generation settings ---
LLM_TEMPERATURE = 0.3
LLM_MAX_TOKENS = 900
